=== AlexLembiewski/AleksandrLembievskij/task5/BankDeposit/src/java/by/epam/task5/bankdeposit/data/BankDeposit.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="deposits">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="bank"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="bank">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="country" type="xs:string"/> 
                <xs:element name="type" type="typeOfAccount"/>
                <xs:element name="depositor" type="xs:string"/>
                <xs:element name="accountId" type="Id"/>
                <xs:element name="amount" type="xs:int"/>
                <xs:element name="profitability">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="timeConstraints" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="typeOfAccount">
        <xs:restriction base="xs:string">
            <xs:enumeration value="poste restante"></xs:enumeration>
            <xs:enumeration value="urgent"></xs:enumeration>
            <xs:enumeration value="calculated"></xs:enumeration>
            <xs:enumeration value="cumulative"></xs:enumeration>
            <xs:enumeration value="saving"></xs:enumeration>
            <xs:enumeration value="metal"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Id">
        <xs:restriction base="xs:ID">
            <xs:pattern value="N[\d]{4}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== AlexLembiewski/AleksandrLembievskij/task4/BankDeposit/src/by/epam/task04/bankdeposit/BankDeposit.xml
<?xml version="1.0" encoding="UTF-8"?>
<deposits xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="BankDeposit.xsd">
    <bank>
        <name>Priorbank</name>
        <country>BY</country>
        <type>calculated</type>
        <depositor>Ivanov Ivan Ivanovich</depositor>
        <accountId>N1234</accountId>
        <amount>1000000</amount>
        <profitability>10</profitability>
        <timeConstraints>180</timeConstraints>
    </bank>
    <bank>
        <name>Belarusbank</name>
        <country>BY</country>
        <type>saving</type>
        <depositor>Petrov Petr Petrovich</depositor>
        <accountId>N5678</accountId>
        <amount>5000000</amount>
        <profitability>12</profitability>
        <timeConstraints>365</timeConstraints>
    </bank>
</deposits>
